name: "Issue/PR Tag"
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  push:
    paths:
      - .github/workflows/issue-pr-create.yml

jobs:
  notify:
    uses: devops-actions/.github/.github/workflows/issue-pr-tag.yml@main
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      org_name: ${{ vars.FIXED_ORG_NAME }}
      tag_team: ${{ vars.TAG_TEAM }}
